### Q2

In [1]:
from sklearn.datasets import load_breast_cancer

In [2]:
data = load_breast_cancer()

In [3]:
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0

In [4]:
X = data.data


In [5]:
y = data.target

In [6]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X = sc_x.fit_transform(X) 

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

### Logistic Regression

### Default Values

In [9]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
import numpy as np

classifier = LogisticRegression(C=1.0,max_iter=100)

'''Cfloat, default=1.0
Inverse of regularization strength; must be a positive float. 
Like in support vector machines, smaller values specify stronger regularization.'''
'''max_iterint, default=100
Maximum number of iterations taken for the solvers to converge.'''

classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

cm = confusion_matrix(y_test, y_pred)

Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance

print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))
print("The Variance is:",Variance)
print("The bias is:",Bias)

Confusion Matrix : 
 [[41  2]
 [ 1 70]]
Training_Accuracy: 0.9868131868131869
Testing Accuracy :  0.9736842105263158
The Variance is: 0.23268698060941828
The bias is: 0.0010953755677696742


In [19]:
from mlxtend.evaluate import bias_variance_decomp

In [23]:
from sklearn import metrics
from sklearn.metrics import mean_squared_error 

classifier = LogisticRegression(C=1.0,max_iter=100)
classifier.fit(X_train, y_train)

mse, bias, var = bias_variance_decomp(classifier, X_train, y_train, X_test, y_test, loss='mse', num_rounds=200, random_seed=123)
y_pred=classifier.predict(X_test)
# summarize results
print('MSE from bias_variance lib [avg expected loss]: %.3f' % mse)
print('Avg Bias: %.3f' % bias)
print('Avg Variance: %.3f' % var)
print('Mean Square error by Sckit-learn lib: %.3f' % metrics.mean_squared_error(y_test,y_pred))

MSE from bias_variance lib [avg expected loss]: 0.022
Avg Bias: 0.015
Avg Variance: 0.007
Mean Square error by Sckit-learn lib: 0.026


### Changing Values

In [ ]:
''' C is the inverse of regularization strength.
It's expected to consume more iterations and may lead to overfit the model.
A high value of C tells the model to give high weight to the training data, and a lower weight to the complexity penalty. 
A low value tells the model to give more weight to this complexity penalty at the expense of fitting to the training data.
Basically, a high C means "Trust this training data a lot", while a low value says "This data may not be fully representative
of the real world data, so if it's telling you to make a parameter really large, don't listen to it".'''

In [43]:
classifier = LogisticRegression(C=0.1,max_iter=100)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)  
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))

The Variance is: 0.2303016312711603
The bias is: 0.0036306966967259713
Confusion Matrix : 
 [[41  2]
 [ 0 71]]
Training_Accuracy: 0.9802197802197802
Testing Accuracy :  0.9824561403508771


In [44]:
classifier = LogisticRegression(C=10,max_iter=100)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)  
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))

The Variance is: 0.23699599876885197
The bias is: -0.0030519056559785707
Confusion Matrix : 
 [[42  1]
 [ 2 69]]
Training_Accuracy: 0.989010989010989
Testing Accuracy :  0.9736842105263158


In [45]:
classifier = LogisticRegression(C=10,max_iter=200)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)  
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))

The Variance is: 0.23699599876885197
The bias is: -0.0030519056559785707
Confusion Matrix : 
 [[42  1]
 [ 2 69]]
Training_Accuracy: 0.989010989010989
Testing Accuracy :  0.9736842105263158


In [46]:
classifier = LogisticRegression(C=100,max_iter=200)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred) 
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))

The Variance is: 0.2437673130193906
The bias is: -0.007653023966817413
Confusion Matrix : 
 [[42  1]
 [ 6 65]]
Training_Accuracy: 0.9934065934065934
Testing Accuracy :  0.9385964912280702


In [47]:
classifier = LogisticRegression(C=100,max_iter=300)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred)  
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))

The Variance is: 0.2437673130193906
The bias is: -0.007653023966817413
Confusion Matrix : 
 [[42  1]
 [ 6 65]]
Training_Accuracy: 0.9934065934065934
Testing Accuracy :  0.9385964912280702


In [48]:
classifier = LogisticRegression(C=1000,max_iter=400)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred) 
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))

The Variance is: 0.2437673130193906
The bias is: -0.007653023966817413
Confusion Matrix : 
 [[42  1]
 [ 6 65]]
Training_Accuracy: 1.0
Testing Accuracy :  0.9385964912280702


In [49]:
classifier = LogisticRegression(C=10000,max_iter=500)
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)
cm = confusion_matrix(y_test, y_pred) 
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print ("Confusion Matrix : \n", cm)
print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))

The Variance is: 0.2437673130193906
The bias is: -0.007653023966817413
Confusion Matrix : 
 [[42  1]
 [ 6 65]]
Training_Accuracy: 1.0
Testing Accuracy :  0.9385964912280702


D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [10]:
C = [1,0.2,0.1,10,50,100,150,1000]
max_iter = [100,300,600,900,1000,1300,1500,1700]
for i in C:
    for j in max_iter:
        classifier = LogisticRegression(C=i,max_iter=j)
        classifier.fit(X_train, y_train)
        y_pred = classifier.predict(X_test)
        cm = confusion_matrix(y_test, y_pred)
        Variance = np.var(y_pred)
        SSE = np.mean((np.mean(y_pred)-y)**2)
        Bias = SSE-Variance
    print("The Variance is:",Variance)
    print("The bias is:",Bias)
    print("Training_Accuracy:",accuracy_score(y_train,classifier.predict(X_train)))
    print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))
    print("\n")
    
    


The Variance is: 0.23268698060941828
The bias is: 0.0010953755677696742
Training_Accuracy: 0.9868131868131869
Testing Accuracy :  0.9736842105263158


The Variance is: 0.2303016312711603
The bias is: 0.0036306966967259713
Training_Accuracy: 0.9846153846153847
Testing Accuracy :  0.9824561403508771


The Variance is: 0.2303016312711603
The bias is: 0.0036306966967259713
Training_Accuracy: 0.9802197802197802
Testing Accuracy :  0.9824561403508771


The Variance is: 0.23699599876885197
The bias is: -0.0030519056559785707
Training_Accuracy: 0.989010989010989
Testing Accuracy :  0.9736842105263158




D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


The Variance is: 0.24068944290550937
The bias is: -0.005968038834174211
Training_Accuracy: 0.9934065934065934
Testing Accuracy :  0.956140350877193




D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


The Variance is: 0.2437673130193906
The bias is: -0.007653023966817413
Training_Accuracy: 0.9934065934065934
Testing Accuracy :  0.9385964912280702




D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


The Variance is: 0.2437673130193906
The bias is: -0.007653023966817413
Training_Accuracy: 0.9934065934065934
Testing Accuracy :  0.9385964912280702




D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
D:\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_resu

The Variance is: 0.2437673130193906
The bias is: -0.007653023966817413
Training_Accuracy: 1.0
Testing Accuracy :  0.9385964912280702




### SVM POLY

#### Default

In [50]:
from sklearn import svm
model = svm.SVC(kernel='poly', degree=2,C=1.0, max_iter=-1)
model.fit(X_train, y_train)
print("2nd degree polynomial Kernel")
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print("Training_Accuracy:",accuracy_score(y_train,model.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))


2nd degree polynomial Kernel
The Variance is: 0.15027700831024932
The bias is: 0.1189723916673564
Training_Accuracy: 0.8681318681318682
Testing Accuracy :  0.7894736842105263


#### Varying C and max_iter

In [51]:
from sklearn import svm
C = [1.0,0.1,2.0,10,20,100,500,1000]
max_iter = [-1,1000,2000,5000,7000,10000,20000,30000]
for i in C:
    for j in max_iter:
        model = svm.SVC(kernel='poly', degree=2, C=i,max_iter=j)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        confusion_matrix(y_test, y_pred)
        Variance = np.var(y_pred)
        SSE = np.mean((np.mean(y_pred)-y)**2)
        Bias = SSE-Variance
    print("The Variance is:",Variance)
    print("The bias is:",Bias)
    print("Training_Accuracy:",accuracy_score(y_train,model.predict(X_train)))
    print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))
    print("\n")


The Variance is: 0.15027700831024932
The bias is: 0.1189723916673564
Training_Accuracy: 0.8681318681318682
Testing Accuracy :  0.7894736842105263


The Variance is: 0.11426592797783934
The bias is: 0.17758228704681883
Training_Accuracy: 0.7582417582417582
Testing Accuracy :  0.7543859649122807


The Variance is: 0.16104955370883348
The bias is: 0.10189805596530718
Training_Accuracy: 0.8813186813186813
Testing Accuracy :  0.7894736842105263




D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3

The Variance is: 0.18528778085564787
The bias is: 0.06459848940947632
Training_Accuracy: 0.9252747252747253
Testing Accuracy :  0.8157894736842105


The Variance is: 0.19390581717451527
The bias is: 0.05183317186686068
Training_Accuracy: 0.9428571428571428
Testing Accuracy :  0.8333333333333334


The Variance is: 0.20567867036011078
The bias is: 0.0349935981383484
Training_Accuracy: 0.9736263736263736
Testing Accuracy :  0.8596491228070176


The Variance is: 0.21606648199445982
The bias is: 0.020924107512329038
Training_Accuracy: 0.9956043956043956
Testing Accuracy :  0.8333333333333334




D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=1000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=2000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=5000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=7000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'
D:\Anaconda3

The Variance is: 0.2303016312711603
The bias is: 0.0036306966967259713
Training_Accuracy: 1.0
Testing Accuracy :  0.8245614035087719




D:\Anaconda3\lib\site-packages\sklearn\svm\_base.py:255: ConvergenceWarning: Solver terminated early (max_iter=10000).  Consider pre-processing your data with StandardScaler or MinMaxScaler.
  warnings.warn('Solver terminated early (max_iter=%i).'


### SVM RBF

#### Default

In [52]:
from sklearn import svm
model = svm.SVC(kernel='rbf',C=1.0,max_iter=-1)
model.fit(X_train, y_train)
print("2nd degree polynomial Kernel")
y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)
Variance = np.var(y_pred)
SSE = np.mean((np.mean(y_pred)-y)**2)
Bias = SSE-Variance
print("The Variance is:",Variance)
print("The bias is:",Bias)
print("Training_Accuracy:",accuracy_score(y_train,model.predict(X_train)))
print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))


2nd degree polynomial Kernel
The Variance is: 0.23268698060941828
The bias is: 0.0010953755677696742
Training_Accuracy: 0.9868131868131869
Testing Accuracy :  0.9736842105263158


#### Varying C and max_iter

In [11]:
from sklearn import svm
C = [1.0,0.1,2.0,10,20,100,500,1000]
max_iter = [-1,1000,2000,5000,7000,10000,20000,30000]
for i in C:
    for j in max_iter:
        model = svm.SVC(kernel='rbf',C=i,max_iter=j)
        model.fit(X_train, y_train)
        y_pred = model.predict(X_test)
        confusion_matrix(y_test, y_pred)
        Variance = np.var(y_pred)
        SSE = np.mean((np.mean(y_pred)-y)**2)
        Bias = SSE-Variance
    print("The Variance is:",Variance)
    print("The bias is:",Bias)
    print("Training_Accuracy:",accuracy_score(y_train,model.predict(X_train)))
    print ("Testing Accuracy : ", accuracy_score(y_test, y_pred))
    print("\n")


The Variance is: 0.23268698060941828
The bias is: 0.0010953755677696742
Training_Accuracy: 0.9868131868131869
Testing Accuracy :  0.9736842105263158


The Variance is: 0.2303016312711603
The bias is: 0.0036306966967259713
Training_Accuracy: 0.9560439560439561
Testing Accuracy :  0.9473684210526315


The Variance is: 0.2303016312711603
The bias is: 0.0036306966967259713
Training_Accuracy: 0.9912087912087912
Testing Accuracy :  0.9824561403508771


The Variance is: 0.23268698060941828
The bias is: 0.0010953755677696742
Training_Accuracy: 0.9934065934065934
Testing Accuracy :  0.9736842105263158


The Variance is: 0.23491843644198215
The bias is: -0.001132158549798451
Training_Accuracy: 0.9956043956043956
Testing Accuracy :  0.9649122807017544


The Variance is: 0.24068944290550937
The bias is: -0.005968038834174211
Training_Accuracy: 1.0
Testing Accuracy :  0.9385964912280702


The Variance is: 0.24068944290550937
The bias is: -0.005968038834174211
Training_Accuracy: 1.0
Testing Accuracy